In [1]:
import numpy as np
a1=np.array([3,4,5,6,7])
print(a1)

[3 4 5 6 7]


In [5]:
import numpy as np
a1=np.array([[3,4,5],[1,2,3],[2,4,6]])
print(a1)
print(a1.ndim)
print(a1.itemsize)
print(a1.itemsize)
print(a1.dtype)
print("total elements:",a1.size)
print("shape of array is:",a1.shape)


[[3 4 5]
 [1 2 3]
 [2 4 6]]
2
4
4
int32
total elements: 9
shape of array is: (3, 3)


In [9]:
import numpy as np
a1=np.array([[3,4],[1,2],[2,4]])
print(a1)
print(a1.shape)
a2=a1.reshape(2,3)
print(a2)
print(a2.shape)
print(a2[0,2])


[[3 4]
 [1 2]
 [2 4]]
(3, 2)
[[3 4 1]
 [2 2 4]]
(2, 3)
1


In [17]:
import numpy as np
a1=np.array([3,4,78,1,2,8,9])
print("array is:",a1)
print("max element:",a1.max())
print("min element:",a1.min())
print("sum of elements:",a1.sum())
a2=np.array([[10,15,20],[45,35,55],[40,100,110]])
print(a2)
print("max from each row:",a2.max(axis=1))
print("max from each column:",a2.max(axis=0))
print("sum from each row:",a2.sum(axis=1))
print("sum from each column:",a2.sum(axis=0))
print(np.sqrt(a2))
print(np.std(a2))

array is: [ 3  4 78  1  2  8  9]
max element: 78
min element: 1
sum of elements: 105
[[ 10  15  20]
 [ 45  35  55]
 [ 40 100 110]]
max from each row: [ 20  55 110]
max from each column: [ 45 100 110]
sum from each row: [ 45 135 250]
sum from each column: [ 95 150 185]
[[ 3.16227766  3.87298335  4.47213595]
 [ 6.70820393  5.91607978  7.41619849]
 [ 6.32455532 10.         10.48808848]]
33.59159212851328


In [28]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(a1+a2)
print(a1*a2)
print(a2-a1)
print(a2/a1)
b1=np.vstack((a1,a2))  # syntax:- np.vstack(tuple)
b2=np.hstack((a1,a2))  #
print(b1)
print(b2)
      

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[10.          5.5         4.        ]
 [ 3.25        2.8         2.5       ]
 [ 2.28571429  2.125       2.        ]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [31]:
import numpy as np
d1=np.dtype(np.int32)
print(d1)
d2=np.dtype([("salary",np.float)])
print(d2)
d3=np.array([[1,2,3],[4,5,6]],dtype=d1)
print(d3)

int32
[('salary', '<f8')]
[[1 2 3]
 [4 5 6]]


In [196]:
#doubt
import numpy as np
a1=np.empty((3,2),dtype=int)
a2=np.zeros((4,2),dtype=int)
a3=np.ones((2,4),dtype=float)
print(a1)
print(a2)
print(a3)

[[ 1  2]
 [ 3  4]
 [ 5 67]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
import numpy as np
l1=[1,2,3,4,5,67]
l2=(3,5,7,9,112,233)
a1=np.asarray(l1)
a2=np.asarray(l2)
print(a1)
print(a2)
a3=np.arange(10,100,3)
print(a3)

[ 1  2  3  4  5 67]
[  3   5   7   9 112 233]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [182]:
import numpy as np
l1=np.array([1,2,3,4,5,67])
l2=np.array([3,5,7,9,112,233])
l3=np.array([5,6,7,9,8,10,15])
print(l1*l2)
print(l1*l3) # broadcasting error

ValueError: operands could not be broadcast together with shapes (7,) (6,) 

In [200]:
#doubt broadcasting
import numpy as np  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8]) 
print(a)
print(b)
c = a + b;  
print(c)
print(a*b)  #matrix rules are not holding here

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
[2 4 6 8]
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]
[[  2   8  18  32]
 [  4  16  30  48]
 [ 20  80 234  24]]


In [197]:
a=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
b=np.array([2,9,8,7])
print(a*b)
print(a+b)

[[ 2 18 24 28]
 [ 8 45 48 49]
 [16 81 80 77]]
[[ 3 11 11 11]
 [ 6 14 14 14]
 [10 18 18 18]]


In [69]:
#np,nditer is iterator
import numpy as np
arr1=np.array([5,9,6,7,8,76])
for i in np.nditer(arr1):
    print(i,end="      ")
print("\n")
arr2=np.array([[4,5,6,7],[8,9,10,11],[13,20,22,24]])
for i in np.nditer(arr2):
    print(i,end="   ")

5      9      6      7      8      76      

4   5   6   7   8   9   10   11   13   20   22   24   

In [70]:
import numpy as np

print(np.__version__)

1.19.2


In [76]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original matrix")
print(a)
t=a.T
print("transpose matrix")
print(t)
print("modifying matrix")
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=3*x
    print(x,end=" ")

original matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]
modifying matrix
3 6 9 12 15 18 21 24 27 

In [188]:
# doubtimport numpy as np
print(np.char.add([['welcome'],['to'],['pune']])
print(np.char.multiply(['hello'],3))
print(np.char.center("javapoint",20,fillchar="*"))
print(np.char.capitalize("welcome to Aurangabad city"))
print(np.char.title("chapter number one")) 
print(np.char.lower("WELCOME"))
print(np.char.upper("welcome"))
print(np.char.split("welcome to python data science"),sep=" ")
print(np.char.splitlines("Welcome \n to \n javapoint"))
str="how are you"
print(str)
print(np.char.strip(str))
print(np.char.join(":",str))

SyntaxError: invalid syntax (<ipython-input-188-064903797483>, line 4)

In [189]:
# doubt
import numpy as np
a=np.char.add([['welcome'],['to'],['pune']])
print(a)

TypeError: _binary_op_dispatcher() missing 1 required positional argument: 'x2'

In [94]:
import numpy as np
print(np.char.multiply(["hello"],3))

['hellohellohello']


In [110]:
import numpy as np
print(np.char.center("javapoint",100,fillchar ="*"))

*********************************************javapoint**********************************************


In [112]:
import numpy as np
print(np.char.capitalize("welcome to Aurangabad city"))

Welcome to aurangabad city


In [113]:
import numpy as np
print(np.char.title("chapter number one")) 

Chapter Number One


In [114]:
import numpy as np
print(np.char.lower("WELCOME"))
print(np.char.upper("welcome"))

welcome
WELCOME


In [137]:
import numpy as np
print(np.char.split(("welcome to pyt-hon data science"),sep="-"))
print(np.char.split(("welcome to python data science"),sep=" "))
print(np.char.split(("welcome, t,o pyt,hon da,ta scie,nce"),sep=","))

['welcome to pyt', 'hon data science']
['welcome', 'to', 'python', 'data', 'science']
['welcome', ' t', 'o pyt', 'hon da', 'ta scie', 'nce']


In [145]:
import numpy as np
print(np.char.splitlines("Welcome \n to \n javapoint",keepends=False))
print(np.char.splitlines("Welcome \n to \n javapoint",keepends=True))
print(np.char.splitlines("Welcome \n to \n javapoint",keepends=None))
print(np.char.splitlines("Welcome \n to \n javapoint"))



['Welcome ', ' to ', ' javapoint']
['Welcome \n', ' to \n', ' javapoint']
['Welcome ', ' to ', ' javapoint']
['Welcome ', ' to ', ' javapoint']


In [158]:
str=("how are you?")
print(str)
abc="       mynameisdan   "
print(abc)
print(np.char.strip(abc))
print(np.char.join(":",str))
print(np.char.join("^",str))

how are you?
       mynameisdan   
mynameisdan
h:o:w: :a:r:e: :y:o:u:?
h^o^w^ ^a^r^e^ ^y^o^u^?


In [168]:
import numpy as np
a=np.array([[10,9,15],[2,25,17],[20,18,11]])
print(a)
print(np.sort(a))
print("sorting along rows")
print(np.sort(a,0)) #sorts along the columns
print(np.sort(a,1)) #sorts along the rows
data_type=np.dtype([("name","S10"),("marks",int)]) # s10 is datatype of string, int is datatype of marks
print(data_type)
arr=np.array([("mukesh",200),
             ("ajay",350),
             ("vijay",250)], dtype=data_type)
print("sort by name")
print(np.sort(arr,order="name"))
print(np.sort(arr,order="marks"))

[[10  9 15]
 [ 2 25 17]
 [20 18 11]]
[[ 9 10 15]
 [ 2 17 25]
 [11 18 20]]
sorting along rows
[[ 2  9 11]
 [10 18 15]
 [20 25 17]]
[[ 9 10 15]
 [ 2 17 25]
 [11 18 20]]
[('name', 'S10'), ('marks', '<i4')]
sort by name
[(b'ajay', 350) (b'mukesh', 200) (b'vijay', 250)]
[(b'mukesh', 200) (b'vijay', 250) (b'ajay', 350)]


In [191]:
#assigning array
import numpy as np
a=np.array([[10,9,15,19],[2,25,17,21],[20,18,11,23]])
print("original array",a)
print("id of array:",id(a))
b=a
print("copied array:",b)
print("id of array:",id(b))
b.shape=4,3
print(a)
print(b)



original array [[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
id of array: 2698240668416
copied array: [[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
id of array: 2698240668416
[[10  9 15]
 [19  2 25]
 [17 21 20]
 [18 11 23]]
[[10  9 15]
 [19  2 25]
 [17 21 20]
 [18 11 23]]


In [193]:
#view
import numpy as np
a=np.array([[10,9,15,19],[2,25,17,21],[20,18,11,23]])
print("original array",a)
print("id of array:",id(a))
b=a.view()
print("copied array:",b)
print("id of array:",id(b))
b.shape=4,3
print(a)
print(b)

original array [[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
id of array: 2698241407376
copied array: [[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
id of array: 2698241406336
[[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
[[10  9 15]
 [19  2 25]
 [17 21 20]
 [18 11 23]]


In [194]:
#copy
import numpy as np
a=np.array([[10,9,15,19],[2,25,17,21],[20,18,11,23]])
print("original array",a)
print("id of array:",id(a))
b=a.copy()
print("copied array:",b)
print("id of array:",id(b))
b.shape=4,3
print(a)
print(b)

original array [[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
id of array: 2698241329392
copied array: [[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
id of array: 2698241311568
[[10  9 15 19]
 [ 2 25 17 21]
 [20 18 11 23]]
[[10  9 15]
 [19  2 25]
 [17 21 20]
 [18 11 23]]


In [215]:

import numpy as np
a=np.array([[10,9,15,19],[2,25,17,21],[20,18,11,23]])
b=np.array([[1,9,5,9],[2,5,7,21],[2,18,1,3]])
c=np.array([[1,2,3],[4,4,4],[2,2,2]])
d=np.array([[3,3,3],[4,4,4],[6,6,6]])
res1=np.multiply(c,d) #element wise matrix multplication
print(res1)
print("\n")
print(c*d)
print("\n")
res1_1=np.matmul(c,d) #matrix multiplication of arrays 
res1_2=np.dot(c,d) #dot product of matrix
res1_3=np.matmul(d,c)
print(res1_1)
print("\n")
print(res1_2)
print("\n")
print(res1_3)
print("\n")
res2=np.multiply(a,b)
print(res)
res3=np.matmul(a,b) #gives error but lite


[[ 3  6  9]
 [16 16 16]
 [12 12 12]]


[[ 3  6  9]
 [16 16 16]
 [12 12 12]]


[[29 29 29]
 [52 52 52]
 [26 26 26]]


[[29 29 29]
 [52 52 52]
 [26 26 26]]


[[21 24 27]
 [28 32 36]
 [42 48 54]]


[[ 10  81  75 171]
 [  4 125 119 441]
 [ 40 324  11  69]]


In [227]:
import numpy as np
a1=np.array([[10,9,15,19],[2,25,17,21],[20,18,11,23],[1,1,1,1]])
b=np.array([[10,9,15,19],[2,25,17,21],[20,18,11,23],[2,2,2,1]])
arr=np.matmul(a1,b)
print(arr)
print("\n")

A = np.array([[5, 0],[0, 5]])
B =np.array([5, 2])
c=np.matmul(A,B)
print(c)


[[ 456  623  506  743]
 [ 452  991  684  975]
 [ 502  874  773 1034]
 [  34   54   45   64]]


[25 10]


In [228]:
import numpy as np
a=np.arange(12) #(start,stop,step)
b=np.where(a<6,a,5*a) #a<6=x,5*a=y  if x then a else y
print(b)

[ 0  1  2  3  4  5 30 35 40 45 50 55]


In [229]:
import numpy as np
b=np.where([[True,False],[True,True]],[[1,2],[3,4]],[[9,8],[7,6]])
print(b)

[[1 8]
 [3 4]]


In [2]:
#The numpy.random.randn() function creates an array of specified shape and fills
#it with random values as per standard normal distribution. 
import numpy as np
p=np.random.randn(45) 
p

array([ 1.0421192 ,  1.21141273,  2.28067358,  2.52174099,  1.59231847,
        0.13922316,  0.69434184,  0.15079818, -1.48979842,  0.88779193,
        0.10778775,  0.70993628,  2.45444509, -0.19288964,  0.90594329,
       -0.21502419,  0.15004847,  0.0355889 ,  0.98262813,  0.17321197,
        1.84409277,  0.81678092,  0.20542204,  0.77765315, -0.55800384,
       -1.24453038,  0.60410487, -2.48967746, -0.11621791, -0.39225324,
       -0.21017239,  0.19230837,  0.27413287,  1.53421081, -0.65564439,
        0.48144991,  0.27983142, -0.81057311,  0.55691726,  1.25625946,
       -0.8031416 ,  1.98543082,  1.08538015, -1.25450392,  0.11726057])

In [34]:
#np.random.randint()  fills array with random integers
import numpy as np
arr1 = np.random.randint(low = 0, high = 30, size = 20)
arr2=np.random.randint( 0,300,80)  #low,high,size
arr3=np.random.randint(23,69,(3,5))  #2D array
arr4=np.random.randint(2, 10, (2, 3, 4))  #3D array
arr5=np.random.randint(2,20) #default size =1
print ("Output 1D Array filled with random integers : \n ", arr1) 
print('\n')
print(arr2)
print('\n')
print("Output 2D Array filled with random integers : \n",arr3)
print('\n')
print("Output 3D Array filled with random integers : \n",arr4)
print('\n')
print(arr5)


Output 1D Array filled with random integers : 
  [12 24  2 22 11  4  9 12 12  7  2 18 18 29 22  4 20 20 17 17]


[282 236 149 172 140  69  84 199 119 113 156 220 269   9 196  42 101 191
 140  92 127 217  31 241  35 285 205 151   9  83 287 151  24 235 110 140
  92 157 199  75 237   9 126 284  76 198 169 202 270 217 167 156 285 224
  23 171  75   1  15 285 111 212  95 238  34  92  83 222 151  18 242 292
 190  28   1  93  81 179 118 285]


Output 2D Array filled with random integers : 
 [[51 64 43 46 52]
 [55 56 41 34 65]
 [45 49 41 49 54]]


Output 3D Array filled with random integers : 
 [[[5 6 3 5]
  [7 4 2 9]
  [7 3 6 7]]

 [[5 5 8 9]
  [2 6 9 8]
  [4 5 8 2]]]


6


In [14]:
#np.random.rand() or np.random.random  fills array with values between (0-1)
import numpy as np
array1 = np.random.rand(5)
print("1D Array filled with random values : \n", array1)

1D Array filled with random values : 
 [0.98152726 0.81027211 0.28766916 0.02383039 0.09221633]


In [20]:
import numpy as np
np.random.seed(0) #can put anything instaed of 0
s=np.random.choice(5,10)  #returns array with no's between 0-5 with size 10
s



array([4, 0, 3, 3, 3, 1, 3, 2, 4, 0])

In [31]:
import numpy as np
np.random.seed(9)
s1=np.random.choice(77,36)  #prints 36 integers between 0-77
s1

array([54, 56, 22, 65, 22, 52, 59, 40, 33,  0, 60, 59, 74, 56, 62, 12, 18,
       56,  1, 56, 11, 37, 19,  9, 56, 49, 63, 13, 59, 58, 33, 54, 63, 22,
       50, 40])

In [37]:
#The random.normal() function is part of Python’s NumPy library and is used to model 
#probabilistic experiments with the help of normal distribution.
import numpy as np
m=6.7
s=1.2
n=2000
ret = np.random.normal(m, s, n) #m=mean , s=std deviation ,n=sample size
print(len(ret))
print(ret.mean())
print(ret)
##the return value has 2000 values, which has m=6.7 , std=1.2
#check the plot in matplotlib module

2000
6.73867291326013
[8.48780091 5.69757887 6.28749654 ... 8.02998891 6.88866749 6.29510166]
